<a href="https://colab.research.google.com/github/rajeshwari9999/01fe22bec416/blob/main/rajeshwarid7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **multivarient linaer regression**

In [5]:
import pandas as pd
import numpy as np


In [7]:
data_df=pd.read_csv('/content/drive/MyDrive/mul.csv')


In [9]:
data_df.head()

x4   x1  x2    x3     y
0  25  100   1  1000  2000
1  29  200   2  1800   250
2  30  300   1  1500   400
3  40  500   4  1000   800
4  50  700   7  1500  1000

In [12]:
x=data_df.drop(['y'],axis=1).values
y=data_df[''].values

In [13]:
print(x)


[[  25  100    1 1000]
 [  29  200    2 1800]
 [  30  300    1 1500]
 [  40  500    4 1000]
 [  50  700    7 1500]]


In [14]:
print(y)


[2000  250  400  800 1000]
